import { PromptModeOption, DetailLevelOption, OutputFormatOption, PromptModifier } from "./types";

export const PROMPT_MODE_OPTIONS: PromptModeOption[] = [
  // Engineering modes
  {
    id: "code",
    label: "Code",
    description: "Write or modify code",
    icon: "{ }",
    color: "bg-claude-orange",
    category: "engineering",
  },
  {
    id: "planning",
    label: "Planning",
    description: "Plan implementation strategy",
    icon: "📋",
    color: "bg-accent-blue",
    category: "engineering",
  },
  {
    id: "brainstorming",
    label: "Brainstorm",
    description: "Explore ideas and approaches",
    icon: "💡",
    color: "bg-accent-purple",
    category: "engineering",
  },
  {
    id: "design",
    label: "Design",
    description: "Architecture and system design",
    icon: "🎨",
    color: "bg-accent-teal",
    category: "engineering",
  },
  {
    id: "database",
    label: "Database",
    description: "Schema design and data modeling",
    icon: "🗄️",
    color: "bg-accent-purple",
    category: "engineering",
  },
  {
    id: "debugging",
    label: "Debug",
    description: "Find and fix issues",
    icon: "🐛",
    color: "bg-accent-rose",
    category: "engineering",
  },
  {
    id: "review",
    label: "Review",
    description: "Analyze existing code",
    icon: "🔍",
    color: "bg-accent-blue",
    category: "engineering",
  },
  {
    id: "documentation",
    label: "Docs",
    description: "Write documentation",
    icon: "📝",
    color: "bg-accent-teal",
    category: "engineering",
  },
  {
    id: "refactoring",
    label: "Refactor",
    description: "Improve code structure",
    icon: "♻️",
    color: "bg-accent-green",
    category: "engineering",
  },
  {
    id: "optimize",
    label: "Optimize",
    description: "Performance and efficiency improvements",
    icon: "⚡",
    color: "bg-accent-teal",
    category: "engineering",
  },
  {
    id: "technical",
    label: "Technical",
    description: "Deep technical explanations",
    icon: "⚙️",
    color: "bg-claude-deep",
    category: "engineering",
  },
  {
    id: "feedback",
    label: "Feedback",
    description: "Get code review or suggestions",
    icon: "💬",
    color: "bg-accent-green",
    category: "engineering",
  },
  {
    id: "skill",
    label: "Skill",
    description: "Create a Claude Code slash command",
    icon: "⚡",
    color: "bg-claude-orange",
    category: "engineering",
  },
  {
    id: "plugin",
    label: "Plugin",
    description: "Build a plugin or extension",
    icon: "🧩",
    color: "bg-accent-purple",
    category: "engineering",
  },
  {
    id: "mcp-server",
    label: "MCP Server",
    description: "Build a Model Context Protocol server",
    icon: "🔌",
    color: "bg-accent-teal",
    category: "engineering",
  },
  {
    id: "cli",
    label: "CLI Tool",
    description: "Build command-line interfaces",
    icon: "▶︎",
    color: "bg-claude-deep",
    category: "engineering",
  },
  {
    id: "api",
    label: "API",
    description: "Design and build API endpoints",
    icon: "🌐",
    color: "bg-accent-blue",
    category: "engineering",
  },
  {
    id: "security-audit",
    label: "Security Audit",
    description: "Vulnerability assessment and hardening",
    icon: "🛡️",
    color: "bg-accent-rose",
    category: "engineering",
  },
  {
    id: "auth-sso",
    label: "Auth / SSO",
    description: "Authentication and single sign-on",
    icon: "🔑",
    color: "bg-accent-blue",
    category: "engineering",
  },
  {
    id: "otp-mfa",
    label: "OTP / MFA",
    description: "Multi-factor and one-time passwords",
    icon: "📲",
    color: "bg-accent-green",
    category: "engineering",
  },
  {
    id: "encryption",
    label: "Encryption",
    description: "Data encryption and key management",
    icon: "🔐",
    color: "bg-claude-deep",
    category: "engineering",
  },
  {
    id: "compliance",
    label: "Compliance",
    description: "SOC 2, GDPR, HIPAA standards",
    icon: "📜",
    color: "bg-accent-teal",
    category: "engineering",
  },
  // Business modes
  {
    id: "summary",
    label: "Summary",
    description: "Summarize content or documents",
    icon: "📄",
    color: "bg-accent-blue",
    category: "business",
  },
  {
    id: "transcript",
    label: "Transcript",
    description: "Summarize meeting transcripts",
    icon: "🎙️",
    color: "bg-accent-purple",
    category: "business",
  },
  {
    id: "report",
    label: "Report",
    description: "Generate detailed reports",
    icon: "📊",
    color: "bg-accent-teal",
    category: "business",
  },
  {
    id: "vendor-compare",
    label: "Vendor Compare",
    description: "Compare vendors or products",
    icon: "⚖️",
    color: "bg-claude-orange",
    category: "business",
  },
  {
    id: "analysis",
    label: "Analysis",
    description: "Analyze data or situations",
    icon: "📈",
    color: "bg-accent-green",
    category: "business",
  },
  {
    id: "email",
    label: "Email",
    description: "Draft professional emails",
    icon: "✉️",
    color: "bg-accent-blue",
    category: "business",
  },
  {
    id: "proposal",
    label: "Proposal",
    description: "Write proposals or pitches",
    icon: "📑",
    color: "bg-accent-purple",
    category: "business",
  },
  {
    id: "meeting-notes",
    label: "Meeting Notes",
    description: "Create action items from notes",
    icon: "📌",
    color: "bg-accent-rose",
    category: "business",
  },
  {
    id: "user-story",
    label: "User Story",
    description: "Write stories with acceptance criteria",
    icon: "📋",
    color: "bg-claude-orange",
    category: "business",
  },
  {
    id: "prd",
    label: "PRD",
    description: "Product requirements document",
    icon: "📊",
    color: "bg-accent-purple",
    category: "business",
  },
  {
    id: "okrs",
    label: "OKRs",
    description: "Objectives and key results",
    icon: "🎯",
    color: "bg-accent-green",
    category: "business",
  },
  {
    id: "stakeholder-update",
    label: "Status Update",
    description: "Stakeholder progress updates",
    icon: "📢",
    color: "bg-accent-blue",
    category: "business",
  },
  {
    id: "release-notes",
    label: "Release Notes",
    description: "User-facing changelogs",
    icon: "🚀",
    color: "bg-accent-teal",
    category: "business",
  },
  {
    id: "incident-report",
    label: "Incident Report",
    description: "Postmortems and root cause",
    icon: "🔥",
    color: "bg-accent-rose",
    category: "business",
  },
  {
    id: "runbook",
    label: "Runbook",
    description: "Operational procedures",
    icon: "📖",
    color: "bg-claude-deep",
    category: "business",
  },
  {
    id: "presentation",
    label: "Presentation",
    description: "Slide deck outlines",
    icon: "🎤",
    color: "bg-accent-purple",
    category: "business",
  },
  {
    id: "faq",
    label: "FAQ",
    description: "Frequently asked questions",
    icon: "❓",
    color: "bg-accent-blue",
    category: "business",
  },
  {
    id: "sow",
    label: "SOW",
    description: "Statements of work",
    icon: "📝",
    color: "bg-accent-green",
    category: "business",
  },
  // Marketing modes
  {
    id: "ad-copy",
    label: "Ad Copy",
    description: "Write advertising headlines and copy",
    icon: "📢",
    color: "bg-claude-orange",
    category: "marketing",
  },
  {
    id: "social-media",
    label: "Social Media",
    description: "Create social posts and campaigns",
    icon: "📱",
    color: "bg-accent-blue",
    category: "marketing",
  },
  {
    id: "landing-page",
    label: "Landing Page",
    description: "Write landing page copy and CTAs",
    icon: "🖥️",
    color: "bg-accent-purple",
    category: "marketing",
  },
  {
    id: "email-campaign",
    label: "Email Campaign",
    description: "Draft email drips and sequences",
    icon: "📧",
    color: "bg-accent-teal",
    category: "marketing",
  },
  {
    id: "video-script",
    label: "Video Script",
    description: "Write scripts for video content",
    icon: "🎬",
    color: "bg-accent-rose",
    category: "marketing",
  },
  {
    id: "ai-avatar",
    label: "AI Avatar",
    description: "Scripts for AI talking-head videos",
    icon: "🤖",
    color: "bg-claude-deep",
    category: "marketing",
  },
  {
    id: "seo-content",
    label: "SEO Content",
    description: "Search-optimized articles and pages",
    icon: "🔍",
    color: "bg-accent-green",
    category: "marketing",
  },
  {
    id: "brand-voice",
    label: "Brand Voice",
    description: "Define or apply brand tone guidelines",
    icon: "🎭",
    color: "bg-accent-purple",
    category: "marketing",
  },
  {
    id: "press-release",
    label: "Press Release",
    description: "Write press releases and media kits",
    icon: "📰",
    color: "bg-accent-blue",
    category: "marketing",
  },
  {
    id: "case-study",
    label: "Case Study",
    description: "Write customer success stories",
    icon: "🏆",
    color: "bg-claude-orange",
    category: "marketing",
  },
  {
    id: "product-launch",
    label: "Product Launch",
    description: "Plan launch messaging and assets",
    icon: "🚀",
    color: "bg-accent-teal",
    category: "marketing",
  },
  {
    id: "influencer-brief",
    label: "Influencer Brief",
    description: "Creator briefs and partnerships",
    icon: "🤝",
    color: "bg-accent-rose",
    category: "marketing",
  },
  // Research modes
  {
    id: "deep-research",
    label: "Deep Research",
    description: "Thorough investigation of a topic",
    icon: "🔬",
    color: "bg-accent-purple",
    category: "research",
  },
  {
    id: "competitive-analysis",
    label: "Competitive",
    description: "Analyze competitors and positioning",
    icon: "⚔️",
    color: "bg-accent-rose",
    category: "research",
  },
  {
    id: "market-research",
    label: "Market Research",
    description: "Market size, segments, and trends",
    icon: "📊",
    color: "bg-claude-orange",
    category: "research",
  },
  {
    id: "literature-review",
    label: "Lit Review",
    description: "Summarize existing research and papers",
    icon: "📚",
    color: "bg-accent-blue",
    category: "research",
  },
  {
    id: "trend-analysis",
    label: "Trend Analysis",
    description: "Identify and analyze emerging trends",
    icon: "📈",
    color: "bg-accent-green",
    category: "research",
  },
  {
    id: "feasibility-study",
    label: "Feasibility",
    description: "Assess viability and requirements",
    icon: "🧪",
    color: "bg-accent-teal",
    category: "research",
  },
  {
    id: "benchmarking",
    label: "Benchmarking",
    description: "Compare against industry standards",
    icon: "📏",
    color: "bg-claude-deep",
    category: "research",
  },
  {
    id: "survey-design",
    label: "Survey Design",
    description: "Create surveys and questionnaires",
    icon: "📋",
    color: "bg-accent-purple",
    category: "research",
  },
  {
    id: "data-synthesis",
    label: "Data Synthesis",
    description: "Combine and synthesize data sources",
    icon: "🧬",
    color: "bg-accent-blue",
    category: "research",
  },
  {
    id: "gap-analysis",
    label: "Gap Analysis",
    description: "Identify gaps between current and target",
    icon: "🔎",
    color: "bg-accent-rose",
    category: "research",
  },
  {
    id: "swot",
    label: "SWOT",
    description: "Strengths, weaknesses, opportunities, threats",
    icon: "🎯",
    color: "bg-claude-orange",
    category: "research",
  },
  {
    id: "due-diligence",
    label: "Due Diligence",
    description: "Thorough investigation before decisions",
    icon: "⚖️",
    color: "bg-accent-green",
    category: "research",
  },
];

export const DETAIL_LEVEL_OPTIONS: DetailLevelOption[] = [
  { id: "concise", label: "Concise", icon: "−" },
  { id: "balanced", label: "Balanced", icon: "○" },
  { id: "comprehensive", label: "Detailed", icon: "+" },
];

export const OUTPUT_FORMAT_OPTIONS: OutputFormatOption[] = [
  {
    id: "structured",
    label: "Structured",
    description: "Clear sections and headers",
  },
  {
    id: "conversational",
    label: "Natural",
    description: "Natural dialogue flow",
  },
  {
    id: "bullet-points",
    label: "Bullets",
    description: "Scannable list format",
  },
];

export const PROMPT_MODIFIERS: PromptModifier[] = [
  // General modifiers
  {
    id: "step-by-step",
    label: "Step-by-Step",
    description: "Break down into clear steps",
    promptAddition: "Please provide a step-by-step breakdown.",
  },
  {
    id: "examples",
    label: "Include Examples",
    description: "Add practical examples",
    promptAddition: "Include relevant examples to illustrate the concepts.",
  },
  {
    id: "alternatives",
    label: "Show Alternatives",
    description: "Suggest different approaches",
    promptAddition: "Also suggest alternative approaches or solutions.",
  },
  {
    id: "best-practices",
    label: "Best Practices",
    description: "Follow industry standards",
    promptAddition: "Follow industry best practices and explain why.",
  },
  {
    id: "explain-reasoning",
    label: "Explain Reasoning",
    description: "Share thought process",
    promptAddition: "Explain your reasoning and decision-making process.",
  },
  // Engineering modifiers
  {
    id: "edge-cases",
    label: "Handle Edge Cases",
    description: "Consider corner cases",
    promptAddition: "Consider and handle potential edge cases.",
  },
  {
    id: "performance",
    label: "Optimize Performance",
    description: "Focus on efficiency",
    promptAddition: "Optimize for performance and explain the optimizations.",
  },
  {
    id: "security",
    label: "Security Focus",
    description: "Prioritize security",
    promptAddition: "Pay special attention to security considerations.",
  },
  {
    id: "testing",
    label: "Include Tests",
    description: "Add test coverage",
    promptAddition: "Include appropriate test cases or testing strategies.",
  },
  {
    id: "typescript",
    label: "TypeScript",
    description: "Use TypeScript types",
    promptAddition: "Use TypeScript with proper type annotations.",
  },
  {
    id: "error-handling",
    label: "Error Handling",
    description: "Robust error handling",
    promptAddition: "Include comprehensive error handling.",
  },
  {
    id: "comments",
    label: "Add Comments",
    description: "Document the code",
    promptAddition: "Add helpful comments to explain complex logic.",
  },
  // Business modifiers
  {
    id: "executive-summary",
    label: "Executive Summary",
    description: "Include high-level overview",
    promptAddition: "Include an executive summary at the beginning.",
  },
  {
    id: "action-items",
    label: "Action Items",
    description: "Extract actionable tasks",
    promptAddition: "Extract and list clear action items with owners if possible.",
  },
  {
    id: "pros-cons",
    label: "Pros & Cons",
    description: "List advantages and disadvantages",
    promptAddition: "Include a pros and cons analysis.",
  },
  {
    id: "timeline",
    label: "Timeline",
    description: "Include time estimates",
    promptAddition: "Include timeline estimates or scheduling considerations.",
  },
  {
    id: "cost-analysis",
    label: "Cost Analysis",
    description: "Consider budget impact",
    promptAddition: "Include cost analysis or budget considerations.",
  },
  {
    id: "risks",
    label: "Risk Assessment",
    description: "Identify potential risks",
    promptAddition: "Identify potential risks and mitigation strategies.",
  },
  {
    id: "stakeholders",
    label: "Stakeholders",
    description: "Consider all parties involved",
    promptAddition: "Consider all stakeholders and their perspectives.",
  },
  {
    id: "metrics",
    label: "Success Metrics",
    description: "Define measurable outcomes",
    promptAddition: "Define clear success metrics and KPIs.",
  },
];

// Prompt building logic (fallback when API unavailable)
export function buildPrompt(
  transcript: string,
  modes: string[],
  detailLevel: string,
  outputFormat: string,
  modifiers: string[],
  contextInfo: string
): string {
  const modeOptions = modes.map(m => PROMPT_MODE_OPTIONS.find(opt => opt.id === m)).filter(Boolean);
  const modifierAdditions = modifiers
    .map(id => PROMPT_MODIFIERS.find(m => m.id === id)?.promptAddition)
    .filter(Boolean)
    .join(" ");

  let prompt = "";

  if (modeOptions.length > 0) {
    const modeInstructions: Record<string, string> = {
      // Engineering
      code: "I need help writing or modifying code.",
      planning: "I need help planning the implementation of a feature or project.",
      brainstorming: "I want to brainstorm ideas and explore different approaches.",
      design: "I need help with architecture or system design.",
      database: "I need help with database schema design, data modeling, entity relationships, or SQL queries.",
      feedback: "I'm looking for feedback and suggestions on my approach.",
      technical: "I need a deep technical explanation.",
      debugging: "I need help debugging an issue.",
      review: "I'd like a code review or analysis.",
      documentation: "I need help writing documentation.",
      refactoring: "I need help refactoring and improving code structure.",
      optimize: "I need help optimizing this code for better performance and efficiency.",
      skill: "I need help creating a Claude Code slash command (skill) — a markdown-based command with parameters, instructions, and output formatting.",
      plugin: "I need help building a plugin or extension for a platform, including manifest, lifecycle hooks, and API integration.",
      "mcp-server": "I need help building a Model Context Protocol (MCP) server that exposes tools and resources for AI assistants like Claude.",
      cli: "I need help building a command-line tool with argument parsing, interactive prompts, help text, and proper exit codes.",
      api: "I need help designing and building API endpoints with routes, validation, authentication, error handling, and documentation.",
      "security-audit": "I need a security audit — vulnerability assessment, OWASP review, threat modeling, and hardening recommendations.",
      "auth-sso": "I need help implementing authentication and single sign-on (SSO) with OAuth 2.0, SAML, OpenID Connect, or session management.",
      "otp-mfa": "I need help implementing multi-factor authentication (MFA) with TOTP, SMS OTP, WebAuthn, or passkeys.",
      encryption: "I need help with data encryption, key management, hashing, TLS configuration, or secrets management.",
      compliance: "I need help meeting compliance standards like SOC 2, GDPR, HIPAA, PCI-DSS — audit controls, data handling, and policy documentation.",
      // Business
      summary: "I need a clear summary of the following content.",
      transcript: "I need to summarize this meeting transcript and extract key points.",
      report: "I need to generate a detailed report.",
      "vendor-compare": "I need to compare vendors or products to make a decision.",
      analysis: "I need to analyze this data or situation.",
      email: "I need to draft a professional email.",
      proposal: "I need to write a proposal or pitch.",
      "meeting-notes": "I need to create organized meeting notes with action items.",
      "user-story": "I need to write a user story with clear acceptance criteria, personas, and edge cases.",
      "prd": "I need to write a product requirements document with goals, scope, success metrics, and constraints.",
      "okrs": "I need to draft OKRs with clear objectives and measurable key results.",
      "stakeholder-update": "I need to write a stakeholder status update covering progress, blockers, risks, and next steps.",
      "release-notes": "I need to write user-facing release notes or a changelog from feature descriptions.",
      "incident-report": "I need to write a post-incident report with timeline, root cause analysis, impact, and action items.",
      "runbook": "I need to create an operational runbook with step-by-step procedures for deployment, troubleshooting, or on-call.",
      "presentation": "I need to outline a presentation or slide deck with key points, narrative flow, and speaker notes.",
      "faq": "I need to build a FAQ document with clear questions and comprehensive answers.",
      "sow": "I need to write a statement of work with scope, deliverables, timeline, and assumptions.",
      // Marketing
      "ad-copy": "I need advertising copy with headlines, hooks, value propositions, CTAs, and A/B test variations.",
      "social-media": "I need social media content with platform-native formatting, hashtags, and engagement hooks.",
      "landing-page": "I need landing page copy with hero messaging, benefit sections, social proof, and conversion CTAs.",
      "email-campaign": "I need an email marketing campaign with subject lines, drip sequences, and personalization.",
      "video-script": "I need a video script with a hook, narrative arc, B-roll direction, and pacing notes.",
      "ai-avatar": "I need an AI avatar script with natural speech, gesture cues, and teleprompter formatting.",
      "seo-content": "I need SEO-optimized content with keyword integration, meta descriptions, and heading hierarchy.",
      "brand-voice": "I need to define or apply brand voice with tone guidelines, vocabulary, and channel adaptations.",
      "press-release": "I need a press release with newsworthiness, inverted pyramid, quotes, and boilerplate.",
      "case-study": "I need a case study with challenge/solution/results, metrics, and customer quotes.",
      "product-launch": "I need product launch content with timeline, channel strategy, and messaging matrix.",
      "influencer-brief": "I need an influencer brief with brand guidelines, key messages, deliverables, and compliance.",
      // Research
      "deep-research": "I need thorough research on a topic — sources, synthesis, findings, and conclusions.",
      "competitive-analysis": "I need a competitive analysis comparing key players, positioning, features, and market share.",
      "market-research": "I need market research on size, segments, growth trends, and customer demographics.",
      "literature-review": "I need a literature review summarizing existing research, methodologies, and key findings.",
      "trend-analysis": "I need trend analysis identifying emerging patterns, drivers, and future projections.",
      "feasibility-study": "I need a feasibility study assessing viability, resources, risks, and ROI potential.",
      "benchmarking": "I need benchmarking against industry standards, best-in-class metrics, and performance gaps.",
      "survey-design": "I need to design a survey with research objectives, question types, and sampling methodology.",
      "data-synthesis": "I need to synthesize multiple data sources into unified insights and actionable conclusions.",
      "gap-analysis": "I need a gap analysis comparing current state to target state with a remediation roadmap.",
      "swot": "I need a SWOT analysis covering strengths, weaknesses, opportunities, and threats.",
      "due-diligence": "I need a due diligence investigation with risk assessment, findings, and recommendations.",
    };
    const instructions = modes.map(m => modeInstructions[m]).filter(Boolean).join("\n");
    prompt += `## Task Type\n${instructions}\n\n`;
  }

  prompt += `## Request\n${transcript}\n\n`;

  if (contextInfo.trim()) {
    prompt += `## Additional Context\n${contextInfo}\n\n`;
  }

  const detailInstructions: Record<string, string> = {
    concise: "Keep the response concise and to the point.",
    balanced: "Provide a balanced level of detail.",
    comprehensive: "Provide a comprehensive and detailed response.",
  };
  prompt += `## Detail Level\n${detailInstructions[detailLevel] || detailInstructions.balanced}\n\n`;

  const formatInstructions: Record<string, string> = {
    structured: "Use clear sections with headers to organize the response.",
    conversational: "Use a natural, conversational tone.",
    "bullet-points": "Format the response as organized bullet points for easy scanning.",
  };
  prompt += `## Output Format\n${formatInstructions[outputFormat] || formatInstructions.structured}\n\n`;

  if (modifierAdditions) {
    prompt += `## Additional Requirements\n${modifierAdditions}\n`;
  }

  return prompt.trim();
}
